name: todo
description: A new flutter plugin project.
version: 0.0.3
author:
homepage: https://github.com/audacioustux/AloPOCs

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  import_js_library: ^1.0.1
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: TodoWeb
        fileName: todo_web.dart
  assets:
    - assets/pingpong.js

